### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by krazyplacebo** [tsutsui/emacs-18.59-netbsd#1]
Compiled under Debian Linux Wheezy and also Manjaro Linux. 

Compiles and runs fine except:

1. Press Alt+x
2. Type help-for-help
3. Press k (for Describe-key)
4. press any key 

causes segmentation fault. GDB reports:

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7c94b3a in __strlen_sse2 () from /usr/lib/libc.so.6

**Comment by tsutsui** [comment]
Confirmed on NetBSD/i386 8.0 (attached) and debian jessie 64bit.
[emacs-18.59-backtrace.txt](https://github.com/tsutsui/emacs-18.59-netbsd/files/2546068/emacs-18.59-backtrace.txt)

Note mule-1.1 doesn't get SIGSEGV. I'll check which change could affect this.

**Comment by tsutsui** [comment]
Could you try 5cd47bd ?
Thanks,

**Comment by krazyplacebo** [comment]
I've just tried out your fixed version and it works flawlessly!
I won't pretend that I fully understand what the problem was, or how you fixed it. I'll just take this
opportunity to thank  you for your work on this project and for fixing this issue. It really is appreciated.
Emacs 18 on today's hardware is a dream come true, so many thanks!

**Comment by tsutsui** [comment]
I'm also glad to see yet another emacs 18 user today. Thanks :-)

**Comment by krazyplacebo** [comment]
Sorry to be a pest but I've come across another (related) problem.

    Alt-x --> help-for-help --> k --> <press any key>

and emacs displays:

    rt with default dir in minibuffer.

which obviously doesn't make any sense. The beginning of the string is missing.

Searching /usr/local/emacs/etc/DOC-18.59.1 shows the complete string should be:

    *Non-nil means when reading a filename start with default dir in minibuffer.

So the first half of the string is not displayed by emacs. 

And this appears to be the wrong string anyway. I have Dell Unix running under qemu which also has emacs 18.59 installed. The same key sequence under Dell unix emacs produces the following output:

    Insert this character.  Prefix arg is repeat-count.
    
If you could please look into this it would be greatly appreciated. Thanks.

**Comment by tsutsui** [comment]
Could you please creat a new issue for it with an exact key sequence and your ~/.emacs settings?
It's a different problem from SEGV and not obvious. At least I cannot reproduce it on debian jessie with Alt-X -> help-for-help -> k -> CTRL+P:
```
$ uname -a
Linux teokurebsd.org 2.6.32-042stab092.2 #1 SMP Tue Jul 8 10:35:55 MSK 2014 x86_64 GNU/Linux
```
![emacs-help-for-help-k-ctrl-p](https://user-images.githubusercontent.com/3054480/48123943-7e929780-e2be-11e8-9574-4fd7fb7b8c58.png)

Thanks,
