### ISSUE TITLE
Incorrect output for help-for-help function

### ISSUE THREAD

**Issue by krazyplacebo** [tsutsui/emacs-18.59-netbsd#2]
I have opened a new issue as you suggested.

The exact key sequence is:

1. press Alt+x
2. type help-for-help
3. Press k
4. press any key (note this has to be a single key, such as a, b, c, etc. - not a key combination like CTRL+p)

If I press 'a' as a single key for example, I get:

-----Emacs: *scratch*              (Lisp Interaction)----All-------------------------------------
self-insert-command:
rt with default dir in minibuffer.

Also my output for CTRL+p does not match yours. I get:

![emacs18](https://user-images.githubusercontent.com/28649761/48127835-95b09580-e27c-11e8-93ba-da1ff20c720a.png)

This is under Manjaro Linux (64-bit). I also get the same result under Debian Wheezy (32-bit)

In Emacs 18.59 under DELL Unix  which I have running in qemu the output for a single key press is:

-----Emacs: *scratch*              (Lisp Interaction)----All-------------------------------------
Self-insert-command:
Insert this character. Prefix arg is repeat-count

All of this is without an .emacs init file.

**Comment by krazyplacebo** [comment]
An update:

I have installed Debian Jessie under qemu and downloaded and compiled Emacs 18. This time it works exactly as it should. I get the same output as yourself. I then recompiled it under Debian Wheezy and it works there too!

The only thing that I did differently this time was to 'sudo make install' after 'make'. Previously I was just compiling Emacs and then manually copying the files under /usr/local/emacs. I was afraid it might mess with my current copy of Emacs otherwise.

I am now closing this issue as  everything is sorted and I apologize for wasting your time. Hey you can't put something from the 1990s out there and not attract at least some old fogies! Thanks again and take care.

**Comment by tsutsui** [comment]
No problem, thanks for your tests and confirmation!
